# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Viv' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Viv

pod 'XLPagerTabStrip'

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'FirebaseUI'
pod 'Firebase/Auth'

pod 'GoogleSignIn'

end
